# Generated by Django 3.2 on 2021-05-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_receipt', models.DateField(verbose_name='Дата приёма')),
                ('nosebleeds', models.PositiveSmallIntegerField(choices=[(1, 'Справа'), (2, 'Слева'), (3, 'Справа и слева'), (4, 'Нет')], default=1, verbose_name='Носовые кровотечения')),
                ('nosebleeds_per_month', models.CharField(max_length=100, verbose_name='Количество носовых кровотечений в месяц')),
                ('abundant_periods', models.PositiveSmallIntegerField(choices=[(1, 'Нет'), (2, 'Да')], default=1, verbose_name='Обильные месячные')),
                ('bleeding_gums', models.PositiveSmallIntegerField(choices=[(1, 'Нет'), (2, 'Да')], default=1, verbose_name='Кровоточивость дёсен')),
                ('bruising', models.PositiveSmallIntegerField(choices=[(1, 'Нет'), (2, 'Да')], default=1, verbose_name='Синячковость')),
                ('other_bleeding', models.CharField(max_length=100, verbose_name='Другая кровоточивость')),
                ('duration_of_bleeding', models.IntegerField(verbose_name='Длительность кровоточивости(мин)')),
                ('fainting', models.PositiveSmallIntegerField(choices=[(1, 'Нет'), (2, 'Да')], default=1, verbose_name='Обмороки')),
                ('dizziness', models.PositiveSmallIntegerField(choices=[(1, 'Нет'), (2, 'Да')], default=1, verbose_name='Головокружения')),
                ('heart_pain', models.PositiveSmallIntegerField(choices=[(1, 'Нет'), (2, 'Да')], default=1, verbose_name='Боль в области сердца')),
                ('others', models.CharField(max_length=100, verbose_name='Другие')),
                ('first_appearance', models.IntegerField(verbose_name='Первое появление, возраст')),
                ('provocation_of_nosebleeds', models.PositiveSmallIntegerField(choices=[(1, 'Утро'), (2, 'День'), (3, 'Ночь'), (4, 'Вечер'), (5, 'Физ нагрузка'), (6, 'Умственная нагрузка'), (7, 'Стресс'), (8, 'Весна'), (9, 'Осень')], default=1, verbose_name='Провокация носовых кровотечений')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
        migrations.AlterField(
            model_name='articles',
            name='father_nation',
            field=models.PositiveSmallIntegerField(choices=[('Русские', 'Русские'), ('Украинцы', 'Украинцы'), ('Немцы', 'Немцы'), ('Казахи', 'Казахи'), ('Белорусы', 'Белорусы'), ('Алтайцы', 'Алтайцы'), ('Кумандинцы', 'Кумандинцы'), ('Татары', 'Татары'), ('ДРУГАЯ', 'ДРУГАЯ')], default=1, verbose_name='Нация отца пациента'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='mother_nation',
            field=models.PositiveSmallIntegerField(choices=[('Русские', 'Русские'), ('Украинцы', 'Украинцы'), ('Немцы', 'Немцы'), ('Казахи', 'Казахи'), ('Белорусы', 'Белорусы'), ('Алтайцы', 'Алтайцы'), ('Кумандинцы', 'Кумандинцы'), ('Татары', 'Татары'), ('ДРУГАЯ', 'ДРУГАЯ')], default=1, verbose_name='Нация матери пациента'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='nation',
            field=models.PositiveSmallIntegerField(choices=[('Русские', 'Русские'), ('Украинцы', 'Украинцы'), ('Немцы', 'Немцы'), ('Казахи', 'Казахи'), ('Белорусы', 'Белорусы'), ('Алтайцы', 'Алтайцы'), ('Кумандинцы', 'Кумандинцы'), ('Татары', 'Татары'), ('ДРУГАЯ', 'ДРУГАЯ')], default=1, verbose_name='Нация пациента'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='sex',
            field=models.PositiveSmallIntegerField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default=1, verbose_name='Пол пациента'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.PositiveSmallIntegerField(choices=[('Пациент', 'Пациент')], default=1, verbose_name='Название'),
        ),
    ]
