# Generated by Django 3.2 on 2021-06-10 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210605_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='name2',
            field=models.CharField(default=1, max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='articles_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.articles'),
        ),
    ]
