# Generated by Django 3.2 on 2021-06-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20210610_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='abundant_periods',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да')], db_column='Обильные месячные', default=4, verbose_name='Обильные месячные'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='abundant_periods2',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да')], default=4, verbose_name='Обильные месячные'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='bleeding_gums',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да')], db_column='Кровоточивость дёсен', default=4, verbose_name='Кровоточивость дёсен'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='bleeding_gums2',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да')], default=4, verbose_name='Кровоточивость дёсен'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='bruising',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да')], db_column='Синячковость', default=4, verbose_name='Синячковость'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='bruising2',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да')], default=4, verbose_name='Синячковость'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='date_receipt',
            field=models.DateField(db_column='Дата приёма', verbose_name='Дата приёма'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='dizziness',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да')], db_column='Головокружения', default=4, verbose_name='Головокружения'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='duration_of_bleeding',
            field=models.IntegerField(db_column='Длительность кровоточивости(мин)', verbose_name='Длительность кровоточивости(мин)'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='fainting',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да')], db_column='Обмороки', default=4, verbose_name='Обмороки'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='father_infarct',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Был ли у отца инфаркт, инсульт, тромбоз до 55 лет'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='first_appearance',
            field=models.IntegerField(db_column='Первое появление, возраст', verbose_name='Первое появление, возраст'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='grand_infarct',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Был ли у деда/бабушки инфаркт, инсульт, тромбоз, до 65 лет'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='heart_pain',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да')], db_column='Боль в области сердца', default=4, verbose_name='Боль в области сердца'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='heart_surgery',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Операции на сердце и сосудах'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='mother_infarct',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Был ли у матери инфаркт, инсульт, тромбоз до 65 лет'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='myocardial_infarction',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Инфаркт миокарда'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='nosebleeds',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Справа'), (2, 'Слева'), (3, 'Справа и слева'), (4, 'Нет')], db_column='Носовые кровотечения', default=4, verbose_name='Носовые кровотечения'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='nosebleeds2',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Справа'), (2, 'Слева'), (3, 'Справа и слева'), (4, 'Нет')], default=4, verbose_name='Носовые кровотечения'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='nosebleeds_per_month',
            field=models.CharField(db_column='Количество носовых кровотечений в месяц', max_length=100, verbose_name='Количество носовых кровотечений в месяц'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='other_bleeding',
            field=models.CharField(db_column='Другая кровоточивость', max_length=100, verbose_name='Другая кровоточивость'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='others',
            field=models.CharField(db_column='Другие', max_length=100, verbose_name='Другие'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='provocation_of_nosebleeds',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Утро'), (7, 'День'), (8, 'Ночь'), (9, 'Вечер'), (10, 'Физ нагрузка'), (11, 'Умственная нагрузка'), (12, 'Стресс'), (13, 'Весна'), (14, 'Осень')], db_column='Провокация носовых кровотечений', default=6, verbose_name='Провокация носовых кровотечений'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='stroke',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Инсульт (ТИА, ОНМК)'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='thrombosis',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Тромбозы'),
        ),
    ]
