# Generated by Django 3.2 on 2021-06-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20210620_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='ari_times_a_year',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='ОРИ > 4 раз в год'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='arrhythmia',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Аритмия'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='atrial_fibrillation',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Фибрилляция предсердий'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='bronchial_asthma',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Бронхиальная астма'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='cancer_disease',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Онкологическое заболевание'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='chronic_gastritis',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Хронический гастрит'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='chronic_pyelonephritis',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Хронический пиелонефрит'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='chronic_tonsillitis',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Хронический тонзиллит'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='diabetes',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Сахарный диабет'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='diseases_of_the_thyroid_gland',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Заболевания щитовидной железы'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='dizziness2',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Головокружения'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='fainting2',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Обмороки'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='flat_feet',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Плоскостопие/гипермобильность суставов'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='heart_defects',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Пороки сердца'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='hypertonic_disease',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Гипертоническая болезнь'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='loss_of_visual_fields',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Выпадение полей зрения'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='migraine',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Мигрени'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='myocardial_dystrophy',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Миокардиодистрофия'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='neuroendocrine_syndrome',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Нейроэндокринный синдром'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='obesity',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Ожирение'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='osteochondrosis',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Остеохондроз'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='varicose_veins',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Варикозная болезнь'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='vegetovascular_dystonia',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Вегето-сосудистая дистония'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='work_of_the_heart',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Нет'), (5, 'Да'), (15, 'Не знаю')], default=4, verbose_name='Перебои в работе сердца'),
        ),
    ]
